export const ADD_INGREDIENT = "ADD_INGREDIENTS";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const SET_INGREDEINTS = "SET_INGREDEINTS";
export const FETCH_INGREDIENTS_FAILED = "FETCH_INGREDIENTS_FAILED";
